#!/usr/bin/python
import redis, getpass, sys, cmd
from PyChannel import app
from PyChannel.objects import Tripcode

class PyChannelAdmin(cmd.Cmd):
	
	def do_create(self, line):
		"Create and admin user. USAGE: pychannel-admin create"
		u_name = raw_input("Enter Username >>> ")
		u_pass = getpass.getpass("Enter Password >>> ")
		u_pass2 = getpass.getpass("Enter Password again >>> ")
		if u_pass != u_pass2:
			print "Passwords do not match"
			sys.exit()
		ctx = app.test_request_context()
		ctx.push()
		app.preprocess_request()
		
		trip = Tripcode(u_name, u_pass, skip_check=True)
		trip.set_permission("admin")
		trip.save()
		
		print "Admin added..."
		
		ctx.pop()
		
if sys.argv < 2:
	PyChannelAdmin.cmdloop()
else:
	ad = PyChannelAdmin()
	ad.onecmd(" ".join(sys.argv[1:]))